import Link from "next/link";
import { requireShopAccess } from "@/lib/auth/shop-access";
import { supabaseAdmin } from "@/lib/supabaseAdmin";

export default async function Page() {
  const access = await requireShopAccess();
  const { data } = await supabaseAdmin.from("exhibition_items").select("id,item_no,product_name,category,quantity,irisu,price,status,published,exhibition_images(id)").eq("shop_id", access.shopId).order("created_at", { ascending: false });
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold">商品管理</h1><p className="mt-2 text-sm text-stone-500">{access.shopName}の商品だけを表示しています。</p></div><div className="flex flex-wrap gap-2"><Link href="/platform/shop/products/new" className="rounded-xl bg-green-800 px-4 py-3 text-sm font-medium text-white">＋ 新規商品登録</Link><Link href="/admin/exhibition/import" className="rounded-xl border border-green-800 bg-white px-4 py-3 text-sm font-medium text-green-800">📄 Excel取込</Link></div></div><section className="mt-6 divide-y overflow-hidden rounded-2xl border bg-white">{(data??[]).map((product)=>{const images=Array.isArray(product.exhibition_images)?product.exhibition_images:[];const ready=Boolean(product.product_name&&product.category&&Number(product.irisu)>0&&Number(product.price)>0);return <article key={product.id} className="grid gap-4 p-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{product.product_name||"商品名未入力"}</p><span className={`rounded-full px-3 py-1 text-xs font-medium ${product.published?"bg-green-50 text-green-800":"bg-stone-100 text-stone-600"}`}>{product.published?"公開中":"下書き"}</span>{!ready&&!product.published&&<span className="rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-700">公開準備中</span>}</div><p className="mt-2 text-xs text-stone-500">No.{product.item_no}・1ケース{product.irisu}鉢入り・{Number(product.price??0).toLocaleString()}円・販売可能{product.quantity??0}ケース</p></div><Link href={`/platform/shop/products/${product.id}`} className="rounded-xl border border-stone-300 px-5 py-2.5 text-center text-sm font-medium text-stone-700 hover:bg-stone-50">編集</Link></article>})}{!data?.length&&<p className="p-10 text-center text-sm text-stone-500">商品はありません。</p>}</section></div>;
}
