-- Mission22: case-based ordering and buyer marketplace settings
alter table public.exhibition_items
  add column if not exists irisu integer;

update public.exhibition_items
set irisu = greatest(coalesce(irisu, units_per_sales_unit, 1), 1);

alter table public.exhibition_items
  alter column irisu set not null,
  alter column irisu set default 1,
  drop constraint if exists exhibition_items_irisu_check,
  add constraint exhibition_items_irisu_check check (irisu >= 1);

comment on column public.exhibition_items.irisu is
  '1ケースに入っている数量。LeiPort_Import_Template_v1.1.xlsx の「入数」。';

alter table public.exhibition_orders
  add column if not exists irisu integer,
  add column if not exists auction_date date,
  add column if not exists order_number text;

update public.exhibition_orders
set irisu = greatest(coalesce(irisu, units_per_sales_unit, 1), 1);

alter table public.exhibition_orders
  alter column irisu set not null,
  alter column irisu set default 1,
  drop constraint if exists exhibition_orders_irisu_check,
  add constraint exhibition_orders_irisu_check check (irisu >= 1);

create unique index if not exists exhibition_orders_order_number_uidx
  on public.exhibition_orders(order_number)
  where order_number is not null;

create table if not exists public.order_number_counters (
  auction_date date primary key,
  last_value integer not null default 0
    check (last_value >= 0 and last_value <= 9999),
  updated_at timestamptz not null default now()
);

revoke all on table public.order_number_counters from anon, authenticated;

create or replace function public.next_lei_port_order_number(
  p_auction_date date
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  next_value integer;
begin
  if p_auction_date is null then
    raise exception 'auction_date is required';
  end if;

  insert into public.order_number_counters (
    auction_date,
    last_value,
    updated_at
  )
  values (p_auction_date, 1, now())
  on conflict (auction_date)
  do update set
    last_value = public.order_number_counters.last_value + 1,
    updated_at = now()
  returning last_value into next_value;

  if next_value > 9999 then
    raise exception 'daily order number limit exceeded for %', p_auction_date;
  end if;

  return
    'LP' ||
    to_char(p_auction_date, 'YYMMDD') ||
    lpad(next_value::text, 4, '0');
end;
$$;

revoke all on function public.next_lei_port_order_number(date) from public;
grant execute on function public.next_lei_port_order_number(date)
  to authenticated;

alter table public.shops
  add column if not exists ordering_enabled boolean not null default false,
  add column if not exists accepts_tuesday boolean not null default true,
  add column if not exists accepts_saturday boolean not null default true,
  add column if not exists order_cutoff_hours integer not null default 24,
  add column if not exists announcement text;

create table if not exists public.favorite_shops (
  user_id uuid not null references auth.users(id) on delete cascade,
  shop_id uuid not null references public.shops(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, shop_id)
);

alter table public.favorite_shops enable row level security;

drop policy if exists "buyers manage own favorite shops" on public.favorite_shops;
create policy "buyers manage own favorite shops"
  on public.favorite_shops
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.order_email_notifications (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.exhibition_orders(id) on delete cascade,
  recipient text not null,
  status text not null default 'pending'
    check (status in ('pending', 'sent', 'failed')),
  error_message text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create index if not exists order_email_notifications_status_idx
  on public.order_email_notifications(status, created_at);
